name: Build and Push latest image

on:
  push:
    # build and push anytime commits are merged to devel
    branches:
      - devel

jobs:
  build_and_push_latest:
    runs-on: ubuntu-20.04
    name: Build and push latest tag from devel and on new commits
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Get short SHA of commit
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e build -- --tag=ghcr.io/${{ github.repository }}:lates --tag=ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Push docker images
        run: |
          docker push --all-tags ghcr.io/${{ github.repository }}
