name: Build and Push latest image

on:
  push:
    # build and push anytime commits are merged to devel
    branches:
      - devel

jobs:
  build_and_push_latest:
    runs-on: ubuntu-20.04
    name: Build and push latest tag from devel and on new commits
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Get short SHA of commit
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
          IMAGE: ghcr.io/${{ github.repository }}
          TAG: ${{ steps.vars.outputs.sha_short }}
        run: |
          TAG=$(echo $TAG | tr '[A-Z]' '[a-z]')
          tox -e docker -- --tag=$IMAGE:$TAG 
          docker tag $IMAGE:$TAG $IMAGE:latest
          docker push $IMAGE:latest 
